### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by th3w1zard1** [ncipollo/release-action#434] opened 2024-03-29 06:39 UTC
**Describe the bug**
This project uses `set-output` which is deprecated and setup to be removed in a later release.

**To Reproduce**
1. Create a workflow using `ncipollo/release-action@v1.10.0`
2. Run it with anything that uploads a release.
3. See a bunch of warnings due to usage of `set-output`

**Expected behavior**
This github action to not be using commands that have been deprecated for over two years.

**Desktop (please complete the following information):**
 - OS: ubuntu-latest
 - Browser N/A
 - Version 1.10.0

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by FriedrichFroebel** [comment] 2024-03-29 06:44
Your version is two years old now - you should probably update to the latest release of the action (version 1.14.0, released about two months ago). This might be a duplicate of #266 as well.

**Closed** 2024-03-29 08:02 UTC

**Comment by th3w1zard1** [comment] 2024-04-04 17:40
Oh I'm so sorry I don't know how I was using an older version. Derp. Thanks for the information.
